apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-guesser-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-guesser
  template:
    metadata:
      labels:
        app: pokemon-guesser
    spec:
      containers:
        - name: pokemon-api
          image: josephpkc/pokemon-api:latest
      imagePullSecrets:
        - name: docker-hub-registry