apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkm-guess-depl
  namespace: pkm-guess
  labels:
    name: "pkm-guess"
  annotations:
    keel.sh/policy: force
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pkm-guess
  template:
    metadata:
      labels:
        app: pkm-guess
    spec:
      containers:
        - name: pkm-data-retrieval
          image: josephpkc/pkm-data-retrieval:latest
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080 # Port for this specific container
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 5
          
---

apiVersion: v1
kind: Service
metadata:
  name: pkm-guess-serv
  namespace: pkm-guess
spec:
  type: LoadBalancer
  selector:
    app: pkm-guess
  ports:
    - name: pkm-guess
      protocol: TCP
      port: 5000 # The Service listens on this port.
      targetPort: 8080 # The Service maps data from the above port to this port, which is where the actual app is.
      
---

apiVersion: forward.webhookrelay.com/v1
kind: WebhookRelayForward
metadata:
  name: keel-forward
spec:
  buckets:
  - name: dockerhub-to-keel
    inputs:
    - name: dockerhub-endpoint
      description: "Public endpoint"
      responseBody: "OK"
      responseStatusCode: 200
    outputs:
    - name: keel
      destination: http://keel:9300/v1/webhooks/dockerhub
      internal: true