on:
  workflow_call:
    inputs:
      name:
        type: string
      dir-path:
        type: string
      sln-name:
        type: string
      docker-tag-name:
        type: string
  push:
    branches: [main]
name: ${{ inputs.name }}
run-name: Build and test ${{ inputs.name }} for PR ( ${{ github.event.number }} ${{ github.event.pull_request.title }}) by ${{ github.actor }}
jobs:
  build-test:
    name: Build and test project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Run tests
        run: dotnet test ./${{ inputs.dir-path }}/${{ inputs.sln-name }}.sln
  docker:
    name: Build and Push Docker
    runs-on: ubuntu-latest
    needs: [build-test]
    steps:
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./${{ inputs.dir-path }}/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.docker-tag-name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  # Currently do not have a Kubernetes cluster online, so won't be able to deploy to it.
  kubernetes:
    needs: [build-test, docker]
    runs-on: ubuntu-latest
    steps:
      - name: Not yet implemented
        run: echo 'Kubernetes cluster not online, nowhere to deploy.'
      #- name: Checkout repo
      #  uses: actions/checkout@v4
      #- name: Deploy to kubernetes
      #  run: |
      #    kubectl apply -f deployment.yaml
      #    kubectl apply -f service.yaml
    
