name: Build and Test Solution
on:
  workflow_call:
    inputs:
      sln-path-name:
        type: string
jobs:
  build-test:
    name: Build and test solution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Install dependencies
        run: dotnet restore ${{ inputs.sln-path-name }}
      - name: Build solution
        run: dotnet build ${{ inputs.sln-path-name }} --configuration Release --no-restore
      - name: Run tests
        run: dotnet test ${{ inputs.sln-path-name }} --configuration Release --no-build
