apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkm-guess-game-depl
  namespace: pkm-guess
  labels:
    name: "pkm-guess-game"
  annotations:
    keel.sh/policy: force
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pkm-guess-game
  template:
    metadata:
      labels:
        app: pkm-guess-game
    spec:
      containers:
        - name: pkm-guess-game
          image: josephpkc/pkm-guess-game:latest
          imagePullPolicy: Always
          ports: 
            - containerPort: 8081 # Port for this specific container

---

apiVersion: v1
kind: Service
metadata:
  name: pkm-guess-game-serv
  namespace: pkm-guess
spec:
  type: NodePort
  selector:
    app: pkm-guess-game
  ports:
    - name: pkm-guess-game
      protocol: TCP
      port: 8081 # The Service listens on this port.
      targetPort: 8081 # The Service maps data from the above port to this port, which is where the actual app is.
