name: PkmWebServer Docker
on:
  push:
    branches: 
      - main
    paths: 
      - 'PkmWebServer/PkmWebServer/**'
  workflow_dispatch:
jobs:
  docker:
    uses: ./.github/workflows/docker.yaml
    with:
      docker-file-path: ./PkmWebServer/Dockerfile
      docker-tag-name: pkm-game
    secrets: inherit
