name: PokemonApi
run-name: Build PokemonApi for ${{ github.event.pull_request.title }} by $${{ github.actor }}
on:
  push:
    branches: [main]
jobs:
  build-test:
    name: Build and test project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Run tests
        run: dotnet test ./PokemonApi/PokemonApi.sln
  docker:
    name: Build and Push Docker
    runs-on: ubuntu-latest
    needs: [build-test]
    steps:
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./PokemonApi/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/pokemon-api:latest
