name: PokemonApi
run-name: Build PokemonApi for PR ( ${{ github.event.number }} ${{ github.event.pull_request.title }}) by ${{ github.actor }}
on:
  push:
    branches: [main]
jobs:
  build-test:
    uses: ./.github/workflows/common/build-test.yaml
    with:
        sln-path: ./PokemonApi/PokemonApi.sln
  build-push-docker:
    needs: [build-test]
    uses: ./.github/workflows/common/build-docker.yaml
    with:
        docker-file-path: ./PokemonApi/Dockerfile
        docker-tag-name: pokemon-api
  deploy-kubernetes:
    needs: [build-test, build-push-docker]
    uses: ./.github/workflows/common/deploy-kubernetes.yaml
    
