name: Build PokemonApi
run-name: Building PokemonApi 🚀
on: [push]
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - 
        name: Run unit tests
        run: dotnet test ./PokemonApi/PokemonApi.sln
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
