name: PkmGuesser Api Docker
on:
  push:
    branches: 
      - main
    paths: 
      - 'PkmWebApi/PkmWebApi/**'
  workflow_dispatch:
jobs:
  docker:
    uses: ./.github/workflows/docker.yaml
    with:
      docker-file-path: ./PkmWebApi/Dockerfile
      docker-tag-name: pkm-guesser-api
    secrets: inherit
