name: Pokemon Guesser Build (Overall)
run-name: Build for PR ( ${{ github.event.number }} ${{ github.event.pull_request.title }}) by ${{ github.actor }}
on:
  push:
    branches: [main]
    # Only build for things outside of a service (typically, CI/CD stuff).
    paths-ignore: ['PkmApi/**', 'PkmDataRetrieval/**']

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yaml
    with:
      sln-path: ./PkmDataRetrieval/PkmDataRetrieval.sln
    
