name: SonarQube
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths: 
      - 'PkmWebApi/**'
  
jobs:
  sonarqube:
    uses: ./.github/workflows/sonarqube.yaml
    with:
      sln-file-path: ./PkmWebApi/PkmWebApi/PkmWebApi.sln
    secrets: inherit