name: PkmGuesser Web Test
on:
  push:
    branches: 
      - main
    paths: 
      - 'PkmWeb/PkmWeb/**'
  workflow_dispatch:
jobs:
  docker:
    uses: ./.github/workflows/test-ng.yaml
    secrets: inherit
